### ISSUE TITLE
Environment specific configuration

### ISSUE THREAD

**Issue by radonm** [CCI-MOC/rhosp-director-config#2]
https://github.com/CCI-MOC/rhosp-director-config/blob/bd3abf45f1a6aecbee3253ee84cfb1b9211c986f/foreman/provisioning_template#L183

Adding route this way is environment specific - isn't it possible to do it other way? Or keep multiple foreman templates - one for each environment ?

**Comment by larsks** [comment]
There are a few ways of handling this.

Perhaps the best way is to invest more effort in configuring the undercloud so that we can just use an existing network for the control plane. I'll spend some time on this once I've got the single sign-on stuff sorted out.

If we treat this network as local to each environment, then we can continue to use the existing configuration.  Each environment gets a dedicated control plane vlan, but they all use the same ip range because they are isolated.

**Comment by radonm** [comment]
There will be some reconfiguration because of https://trello.com/c/6tKJrbod/79-change-vms-and-automation-to-use-2-nics-1gb-link-consumes-a-ton-of-cables-switches-and-adds-little-bandwidth-next-to-2x10gb-not

Seems easiest would be to have that subnet isolated between environments and using same ip range?

**Comment by larsks** [comment]
> Seems easiest would be to have that subnet isolated between environments and using same ip range?

That's probably easiest, yeah. Let's go with that for now.
